### ISSUE TITLE
[bug] Server is crashing while starting

### ISSUE THREAD

**Issue by TheButterbrotMan** [ix0rai/bodaciousberries#39]
**describe the bug**
Crashing while starting server

https://github.com/ix0rai/bodaciousberries/files/8358519/2022-03-27-1.log.gz

**Comment by eristhea** [comment]
thank you for reporting!
this issue should be fixed in bodaciousberries [1.3.2](https://modrinth.com/mod/berries/version/1.3.2), which is being released now. I'm going to be sure to test both the client and the server before release in the future to ensure that I don't release any more server-breaking versions.
